name: tests

on: [push]


jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.6-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 3s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run tests
        env:
          DB_USER=postgres
          DB_PASSWORD=password
          DB_NAME=postgres
          SECRET_KEY=123
          HASH_SALT=NBVCC
          FLASK_ENV=testing
        run: pytest --cov=./ --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
